<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS001-TransferRTGS</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>7663593c-9556-4b5a-90c1-39a78acfceb3</testSuiteGuid>
   <testCaseLink>
      <guid>bfbaed7f-7bba-40aa-ac16-7afac59e799a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TransferRTGS/TC002-TransferRTGSPositive</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0bf8a58-997d-41f2-8755-de4cb77fbde0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>766235c4-593e-4ec6-a3e7-f628f8a1cae1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d7b0d17-3441-4b82-ac82-6d2a182c6243</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5537a6c9-780d-4753-a13a-b548e217a91a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/TransferRTGS/TC001-TransferRTGS</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9ac1d1e-e472-40f4-bf5f-144267158051</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>854d109a-e771-40a5-9aa5-d84b6d040e73</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8389252f-f057-4009-a999-3f339f923fc2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/TransferRTGS/TC003-TransferRTGSPINSalah</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17a031af-b0c2-4e08-9cdf-f917fe2bdb71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2beec0b3-0d94-4098-a3a8-2b2d22238a0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9860710-a4fd-4d99-b889-005a67e8f6b4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
