<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS001-TransferAntarBankRTOL</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>7a9f5be8-d3e7-4a2d-991d-4d65b52eff9c</testSuiteGuid>
   <testCaseLink>
      <guid>3952ce8e-59a3-4fa3-864a-f82b59c0d702</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TransferRTOL/TC002-TransferRTOLPositive</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7de973dd-4bdb-4b24-920d-04571a37dd9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a0f832f-ae2e-4279-9ca6-ebe9d6af6b7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac27a327-f21e-4c5d-aebe-937632516eb5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed7663d8-2538-4e6f-bf47-83e43d3891af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/TransferRTOL/TC001-TransferRTOL</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fccff0d-3a0e-473f-b720-fd6274435ca5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61ec962f-1e95-45b3-94da-7f03d6d474b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eef45633-fa1a-47d0-b1c2-11bf8b8c327e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
